// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"StatusBustImage","status":true,"description":"StatusBustImagePlugin","parameters":{"BustImageX":"640","BustImageY":"620","EquipBustImageX":"500","EquipBustImageY":"620","SkillBustImageX":"","SkillBustImageY":"","MainBustImageX":"500","MainBustImageY":"620","BustPriority":"0","BaseImageOrigin":"2","AddImageOrigin":"2"}},
{"name":"TMSecondName","status":true,"description":"二つ名に実績機能と付け替えによるパラメータ変化を追加します。","parameters":{"secondNameCommand":"称号","defaultSecondNameId":"5","vnSecondNameExp":"1","dateFontSize":"20","equipText":"【装備中】","infoWindowWidth":"240","infoWindowNumberText":"搜集数","infoWindowExpText":"成就分"}},
{"name":"Torigoya_Tween","status":true,"description":"[Base] Tween-animation Engine","parameters":{}},
{"name":"Torigoya_Achievement","status":true,"description":"コモンイベントの注釈で実績システムさん","parameters":{"■ 基本":"","Common Event ID":"1","Storage Key":"Achievement: Game","■ ポップアップ表示":"","Use Popup":"ON","Popup Position":"left","Popup Width":"250","Popup Wait":"0.75","Popup Message":"実績を獲得しました","Popup Sound":"Saint5","■ タイトル/メニュー":"","Use Title":"OFF","Use Menu":"ON","Menu Text":"成就","■ 実績画面":"","List Hidden Title":"？？？？？","List Hidden Description":"(未獲得)","List Hidden Icon":"0","List Cancel Message":"閉じる"}}
];
