// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"StatusBustImage","status":true,"description":"StatusBustImagePlugin","parameters":{"BustImageX":"640","BustImageY":"620","EquipBustImageX":"500","EquipBustImageY":"620","SkillBustImageX":"","SkillBustImageY":"","MainBustImageX":"500","MainBustImageY":"620","BustPriority":"0","BaseImageOrigin":"2","AddImageOrigin":"2"}},
{"name":"TMSecondName","status":true,"description":"二つ名に実績機能と付け替えによるパラメータ変化を追加します。","parameters":{"secondNameCommand":"称号","defaultSecondNameId":"5","vnSecondNameExp":"1","dateFontSize":"20","equipText":"【装備中】","infoWindowWidth":"240","infoWindowNumberText":"搜集数","infoWindowExpText":"成就分"}}
];
